instanceUrl: https://myubiquity.my.salesforce.com
targetUsername: mchapa@myubiquity.com
msTeamsWebhookUrl: null
monitoringDisable:
  - ORG_LIMITS_FILESTORAGE
  - ORG_LIMITS_DATASTORAGE
# docDeployToCloudflare: true

